/*
    OpenMM2 - An Open Source Re-Implementation of Midtown Madness 2
    Copyright (C) 2026 The OpenMM2 contributors

    Structure, conventions and the arts/core runtime follow Open1560 by Brick,
    an Open Source Re-Implementation of Midtown Madness 1. Copyright (C) 2020 Brick.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

#include "core/arts.h"

/*
    MM1 PHYSICS - the whole switch is one directory name.

    Every car's handling is loaded from the folder `vehCarSim::GetDirName` returns, which in retail
    is the constant "tune/vehicle". Point it somewhere else and the entire roster's physics changes
    at once; point it back and the game is byte-for-byte vanilla again. Nothing is patched and
    nothing is overwritten, so "unchecked reverts to MM2" is true by construction rather than by
    carefully undoing a set of edits.

    `tune/vehicle_mm1` is generated by tools/mm1physics.py, which carries MM1's own numbers for
    mass, weight distribution, engine, aerodynamics, suspension and - the big one for how a car
    feels - tyre friction, into MM2's file format. See that script for what is translated, what is
    deliberately left at MM2's values (the transmission, whose two models have no correspondence),
    and which three cars have no MM1 counterpart at all.
*/

// Set by the Physics Options screen. False is retail behaviour in every respect.
extern bool MM1PhysicsEnabled;

// How strongly MM1's numbers are applied, 0.0 (vanilla MM2) to 1.0 (full MM1). The slider on the
// Physics Options screen writes this; it only has meaning while MM1PhysicsEnabled is true.
extern f32 MM1PhysicsBlend;

// Read/write the setting beside the executable so it survives a restart.
void MM1PhysicsLoad();
void MM1PhysicsSave();
