# -*- coding: utf-8 -*-
"""Generate docs/inventory.md: what midtown2.exe contains and what order to port it in.

Ranking is by code size, because size is the honest proxy for effort and the map gives it to us
exactly. The point of the report is to make the next decision obvious rather than to be complete.
"""
import collections
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SYMBOLS = os.path.join(ROOT, "data", "symbols.json")
OUT = os.path.join(ROOT, "docs", "inventory.md")


def main():
    with open(SYMBOLS, encoding="utf-8") as f:
        syms = json.load(f)

    code = [s for s in syms if s["code"]]
    total = sum(s["size"] or 0 for s in code)

    by_class = collections.Counter()
    fns = collections.Counter()
    for s in code:
        key = (s.get("class") or "(free functions)").split("::")[0]
        by_class[key] += s["size"] or 0
        fns[key] += 1

    by_sub = collections.Counter()
    sub_classes = collections.defaultdict(set)
    for s in code:
        by_sub[s["subsystem"]] += s["size"] or 0
        if s.get("class"):
            sub_classes[s["subsystem"]].add(s["class"].split("::")[0])

    virtuals = sum(1 for s in syms if s.get("virtual"))
    vftables = sum(1 for s in syms if s["kind"] == "vftable")

    L = []
    L.append("# midtown2.exe inventory")
    L.append("")
    L.append("Generated by `tools/inventory.py` from `data/symbols.json`. Do not edit by hand.")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Build tag | MM3393 |")
    L.append("| Public symbols | %d |" % len(syms))
    L.append("| Code symbols | %d |" % len(code))
    L.append("| Classes | %d |" % len(set(s["class"].split("::")[0] for s in syms if s.get("class"))))
    L.append("| Virtual methods | %d |" % virtuals)
    L.append("| Vftables | %d |" % vftables)
    L.append("| `.text` covered | %d bytes (%.2f MB) |" % (total, total / 1048576.0))
    L.append("")
    L.append("Every byte of `.text` falls inside a named symbol, so there is no unattributed code.")
    L.append("")
    L.append("## By subsystem")
    L.append("")
    L.append("| Subsystem | Classes | Code bytes | Share |")
    L.append("|---|--:|--:|--:|")

    for sub, size in by_sub.most_common():
        L.append("| `%s` | %d | %d | %.1f%% |" %
                 (sub, len(sub_classes[sub]), size, 100.0 * size / total))

    L.append("")
    L.append("## Largest classes")
    L.append("")
    L.append("Port order follows this table from the bottom up: small, self-contained classes")
    L.append("first, so the tooling and the build are proven before anything hard is attempted.")
    L.append("")
    L.append("| Class | Functions | Code bytes |")
    L.append("|---|--:|--:|")

    for cls, size in by_class.most_common(40):
        L.append("| `%s` | %d | %d |" % (cls, fns[cls], size))

    L.append("")
    L.append("## Smallest classes with real code")
    L.append("")
    L.append("| Class | Functions | Code bytes |")
    L.append("|---|--:|--:|")

    small = sorted((s, c) for c, s in by_class.items() if s > 0)
    for size, cls in small[:25]:
        L.append("| `%s` | %d | %d |" % (cls, fns[cls], size))

    L.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
