# -*- coding: utf-8 -*-
"""Link game.obj into a runnable executable.

At 0% reimplemented this produces a binary that is the original game: every function is still the
original machine code, merely assembled and linked by us instead of shipped by Angel Studios. That
is the point - it is the baseline the port is measured against, and it is what makes each ported
function individually testable.

One setting matters and is not optional:

  -FIXED -BASE   the binary has no relocation table, so it can only run at 0x400000. Anything else
                 and the absolute addresses baked into the code are wrong.

WHY -NODEFAULTLIB IS GONE, AND WHY THAT IS SAFE

midtown2.exe statically linked its own 1999 CRT, and every one of those routines is already in
game.obj under its ordinary C name - `_memcpy`, `_malloc`, `_sprintf`. The original reasoning was
that letting a modern CRT in as well gives duplicate symbols at best and two competing heaps at
worst, so it was kept out entirely.

Dropping the flag does NOT pull a second CRT over the top, because a static library is linked
per-object and on demand. Every CRT symbol game.obj already defines resolves against it, so the
matching library object is never pulled and there is no duplicate and no second heap. What the
flag's removal buys is that a symbol game.obj does NOT define can now be satisfied from libcmt
instead of being a hard link error requiring a hand-written stub in
code/midtown2/core/crtshim.cpp.

BE CLEAR ABOUT HOW SMALL THAT IS. It does not open the standard library. Three separate walls
stand behind this flag, and all three were measured rather than assumed:

  1. libucrt's objects are not self-contained leaf routines. Pulling any one drags the UCRT
     runtime with it - per_thread_data.obj, invalid_parameter.obj, errno.obj - and those reference
     STDCALL-DECORATED Win32 imports (__imp__SetLastError@4) that this link cannot supply. See the
     SYSTEM_LIBS note below.
  2. Nothing needing CRT initialisation works, because the entry point is the game's 1999 `start`
     and the modern initialiser never runs. No printf, no malloc, and therefore no std:: container.
     Use the game's Printf/Displayf and its operator new at 0x577360.
  3. The floating-point routines must stay 1999 anyway. This build is /arch:IA32 so that 80-bit
     x87 intermediates round as they did in 1999; handing pow, fmod, __ftol or the _CI* helpers to
     a modern UCRT would undo the reason that flag is there.

So crtshim.cpp stays. Its contents are exactly the x87 helpers point 3 says must not be shared.
"""
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

OBJ = os.environ.get("MM2_OBJ", r"C:\mm2ghidra\out\game.obj")
OUT = os.path.join(ROOT, "build", "OpenMM2.exe")

# The original entry point, VA 0x00581F5C. Which NAME it carries depends on the Ghidra database:
# data/symbols.json calls it "start", but Ghidra creates its own "entry" label at the image entry
# point and that one can win as the primary symbol. A rebuilt database swapped them, and because
# this constant was declared but never actually passed to the linker, the failure surfaced as
# "unresolved external symbol _WinMainCRTStartup" - the default the linker falls back to when no
# entry point is given, which is nothing to do with the real cause.
#
# So take the name from the assembly rather than assuming either one.
ENTRY_CANDIDATES = ("entry", "start", "WinMainCRTStartup")
IMAGE_BASE = "0x400000"

# All import libraries are generated by tools/implibs.py from the binary's own import table, not
# taken from the SDK. The harness names imports undecorated, and a generated lib matches that
# exactly; the SDK ones carry the stdcall @N suffix and would not resolve.
#
# NOT the CRT. Naming libcmt.lib and libucrt.lib here was tried and does not work, for a reason
# worth recording so it is not tried again: libucrt's objects are not self-contained leaf routines.
# Pulling any of them drags in the UCRT's own runtime - per-thread data, the invalid-parameter
# handler, locale state - and those reference the STDCALL-DECORATED Win32 imports
# (__imp__SetLastError@4). The import libraries here are generated from midtown2.exe's own import
# table and name imports undecorated on purpose, and the SDK libraries that would satisfy the
# decorated form cannot go on the search list because kernel32.lib would shadow KeRNeL32.lib.
#
# So the modern CRT stays reachable only for whatever libcmt can supply without dragging its
# runtime along. See data/crt_shared.json for the fuller finding.
SYSTEM_LIBS = []

# Built by tools/implibs.py from the binary's own import table, because the modern SDK has
# neither DirectPlay nor DirectInput 7.
LOCAL_LIBS = ["IMM32.lib", "KeRNeL32.lib", "USER32.lib", "SHELL32.lib", "DINPUT.lib",
              "DPLAYX.lib", "WINMM.lib", "GDI32.lib", "ADVAPI32.lib", "ole32.lib", "DSOUND.lib"]


def cpp_objects():
    """Compiled reimplementations, which take precedence over the stripped assembly."""
    return sorted(glob.glob(os.path.join(ROOT, "build", "obj", "*.obj")))


def find(pattern, what):
    hits = sorted(glob.glob(pattern))
    if not hits:
        sys.exit("could not find %s (looked for %s)" % (what, pattern))
    return hits[-1]


def resource_object():
    """The compiled icon and version block, when tools/mkres.py managed to produce one.

    Optional on purpose. rc.exe lives in the Windows SDK rather than the MSVC toolchain, and an
    executable without an icon is a cosmetic loss - not a reason to fail a build that is otherwise
    correct. The linker merges a .res into its own .rsrc alongside the embedded DPI manifest.
    """
    res = os.path.join(ROOT, "build", "openmm2.res")
    return [res] if os.path.exists(res) else []


def sdk_bin():
    """The Windows SDK bin directory holding mt.exe.

    -MANIFEST:EMBED makes link.exe shell out to mt.exe, which is not on PATH here; the failure is
    "LNK1158: cannot run 'mt.exe'", which says nothing about where it should have been. The SDK
    version is picked the same way the include directories are.
    """
    import glob as _glob
    root = os.path.join("C:" + os.sep, "Program Files (x86)", "Windows Kits", "10", "bin")
    hits = sorted(_glob.glob(os.path.join(root, "*", "x64", "mt.exe")))
    return os.path.dirname(hits[-1]) if hits else None


def main():
    link = os.environ.get("LINK_EXE") or find(
        r"C:\Program Files\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x86\link.exe",
        "link.exe")

    sdk_lib = find(r"C:\Program Files (x86)\Windows Kits\10\Lib\*\um\x86", "the Windows SDK libs")
    ucrt_lib = sdk_lib.replace(os.sep + "um" + os.sep, os.sep + "ucrt" + os.sep)
    # link.exe sits at <msvc>/bin/Hostx64/x86/link.exe, so the toolchain root is four levels up,
    # not three. This was computed with three for as long as the variable went unused - dropping
    # -NODEFAULTLIB is what first asked the linker to search it, and the symptom was
    # "LNK1104: cannot open file 'LIBCMT.lib'", which says nothing about a malformed path.
    msvc_lib = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(link)))), "lib", "x86")
    for path, what in ((msvc_lib, "the MSVC x86 libraries"), (ucrt_lib, "the UCRT x86 libraries")):
        if not os.path.isdir(path):
            sys.exit("could not find %s at %s" % (what, path))

    if not os.path.exists(OBJ):
        sys.exit("no object at %s - assemble game.asm first" % OBJ)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)

    entry = None
    asm = os.environ.get("MM2_ASM", r"C:\mm2ghidra\out\game.asm")
    if os.path.exists(asm):
        with open(asm, encoding="utf-8", errors="replace") as f:
            declared = set()
            for line in f:
                if line.startswith("PUBLIC "):
                    declared.add(line[7:].strip())
        for name in ENTRY_CANDIDATES:
            if name in declared:
                entry = name
                break
    if entry is None:
        sys.exit("no entry point in %s - looked for %s" % (asm, ", ".join(ENTRY_CANDIDATES)))
    print("entry point: %s" % entry)

    cmd = [
        link,
        "-NOLOGO",
        "-MACHINE:X86",
        "-SUBSYSTEM:WINDOWS",
        "-BASE:" + IMAGE_BASE,
        "-FIXED",
        "-ENTRY:" + entry,

        # uuid.lib is requested by a CRT directive and holds nothing but COM interface GUID
        # constants, which this image already carries in its own data - it is emitted from
        # midtown2.exe's .rdata. It lives only in the SDK's um directory, the one path that must
        # stay off the search list (see the LIBPATH note below), so exclude it by name rather than
        # open that door for one unused library.
        "-NODEFAULTLIB:uuid.lib",

        # A map, so an address in the appended C++ can be named. Without one, a crash
        # inside a reimplementation is just a number: the region past retail's .text has
        # no symbols in data/symbols.json, which only covers the 1999 binary.
        "-MAP:" + os.path.join(ROOT, "build", "OpenMM2.map"),

        # DPI awareness, embedded as a manifest resource.
        #
        # Without it the process is DPI-virtualised: this machine runs its display at 2560x1440 and
        # hands a non-aware process 1920x1080, which is exactly where the game's mode enumeration
        # stopped - so the patched 1440p cap was unreachable no matter what it advertised.
        #
        # A sidecar OpenMM2.exe.manifest does not work: Windows only reads those when
        # HKLM\...\SideBySide\PreferExternalManifest is set, which is a machine-wide setting and
        # not ours to change. Embedding is the supported route and affects only this binary.
        "-MANIFEST:EMBED",
        "-MANIFESTINPUT:" + os.path.join(HERE, "OpenMM2.manifest"),
        # NOTE: the linker builds its own import table and places it in .rdata, on top of the
        # original IAT we already emit as data. That adds ~0x3000 bytes, so .data lands at
        # 0x1C5000 instead of its original 0x1C2000. /MERGE:.idata=... is rejected outright
        # (LNK1272), so this is not fixable from the link line - see docs/harness.md.
        "-OUT:" + OUT,
        # Our own import libraries FIRST. The Windows SDK's um path must not be on the search list
        # at all: filenames are case-insensitive on Windows, so 'KeRNeL32.lib' happily matches the
        # SDK's kernel32.lib, and that one exports the stdcall-decorated __imp__CreateFileA@28
        # rather than the undecorated name this assembly references. Whichever path is searched
        # first wins, and the SDK winning is silent - it just looks like every import is missing.
        "-LIBPATH:" + os.path.join(ROOT, "build", "implibs"),

        # The CRT, needed since -NODEFAULTLIB was dropped - see the note at the top of this file.
        # Only these two directories, and deliberately not sdk_lib: neither holds a Win32 import
        # library, so neither can shadow one of ours the way um/x86 would. libcmt.lib lives in the
        # first and libucrt.lib in the second.
        "-LIBPATH:" + msvc_lib,
        "-LIBPATH:" + ucrt_lib,
        OBJ,
    ] + cpp_objects() + SYSTEM_LIBS + LOCAL_LIBS + resource_object()

    print("link.exe : %s" % link)
    print("sdk libs : %s" % sdk_lib)
    print("object   : %s (%.1f MB)" % (OBJ, os.path.getsize(OBJ) / 1048576.0))
    print()

    # mt.exe is invoked by the linker for -MANIFEST:EMBED and is not on PATH.
    env = dict(os.environ)
    mt = sdk_bin()
    if mt:
        env["PATH"] = mt + os.pathsep + env.get("PATH", "")

    res = subprocess.run(cmd, capture_output=True, text=True, env=env)
    out = (res.stdout or "") + (res.stderr or "")

    unresolved = [l for l in out.splitlines() if "unresolved external" in l]
    errors = [l for l in out.splitlines() if ": error " in l or ": fatal error" in l]

    if unresolved:
        print("%d unresolved externals; first 25:" % len(unresolved))
        for l in unresolved[:25]:
            print("   " + l.strip())
        print()

    other = [l for l in errors if "unresolved external" not in l]
    if other:
        print("other errors:")
        for l in other[:20]:
            print("   " + l.strip())
        print()

    if res.returncode == 0:
        print("linked %s (%.2f MB)" % (OUT, os.path.getsize(OUT) / 1048576.0))
    else:
        print("link failed, exit %d" % res.returncode)

    return res.returncode


if __name__ == "__main__":
    sys.exit(main())
