# -*- coding: utf-8 -*-
"""Check that compiled C++ produces exactly the mangled symbols the original binary used.

This is the guard on the one failure that has no symptom.

A ported function only replaces the original if its symbol name matches EXACTLY. If it does not,
nothing breaks visibly: the C++ object simply contributes an unreferenced symbol, the assembly's
version stays in the link, and the game keeps running the 1999 code. The port looks finished, the
tests pass because they are testing the original, and the divergence is discovered much later in
something unrelated.

The mangled name encodes the return type, every parameter, const-ness and the calling convention,
so a mismatch usually means a signature is subtly wrong - and the most common cause is a type that
looks equivalent but is not. `bool` mangles as `_N`; b32 is an i32 here and mangles as `H`. They
are the same idea and different symbols.

Run after compiling, before trusting a port.
"""
import glob
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Every symbol midtown2.exe actually has. A name outside this set belongs to new code and
# cannot shadow an unported original, so it is not this checker's business.
with open(os.path.join(ROOT, "data", "symbols.json"), encoding="utf-8") as _f:
    GAME_SYMBOLS = {s["mangled"] for s in json.load(_f)}

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

PORTED = os.path.join(ROOT, "data", "ported.json")
OBJDIR = os.path.join(ROOT, "build", "obj")

# dumpbin -symbols emits, with the demangled form appended in parentheses:
#   041 00000000 SECT4 notype () External | ?Mag@Vector3@@QBEMXZ (public: float __thiscall ...)
# so the symbol is the first token after the pipe, not the last token on the line.
SYMBOL = re.compile(r"\|\s+(\S+)")


def find_dumpbin():
    hits = sorted(glob.glob(
        r"C:\Program Files\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x86\dumpbin.exe"))
    if not hits:
        sys.exit("dumpbin.exe not found")
    return hits[-1]


def defined_symbols(dumpbin, obj):
    """Every symbol this object DEFINES (not the ones it merely references)."""
    res = subprocess.run([dumpbin, "-symbols", obj], capture_output=True, text=True)
    out = set()

    for line in res.stdout.splitlines():
        if "External" not in line:
            continue

        # UNDEF means referenced-but-not-defined; those are not ours.
        if "UNDEF" in line:
            continue

        m = SYMBOL.search(line)
        if m:
            out.add(m.group(1))

    return out


def main():
    with open(PORTED, encoding="utf-8") as f:
        expected = set(json.load(f).get("ported", []))

    objs = sorted(glob.glob(os.path.join(OBJDIR, "*.obj")))
    if not objs:
        sys.exit("no objects in %s - compile first" % OBJDIR)

    dumpbin = find_dumpbin()

    found = set()
    for obj in objs:
        found |= defined_symbols(dumpbin, obj)

    print("objects        : %d" % len(objs))
    print("symbols defined: %d" % len(found))
    print("symbols wanted : %d" % len(expected))
    print()

    matched = expected & found
    missing = expected - found

    for sym in sorted(matched):
        print("  OK      %s" % sym)

    for sym in sorted(missing):
        print("  MISSING %s" % sym)

    # A defined symbol that is not on the ported list is not automatically wrong - inline helpers
    # and compiler-generated code land here too - but a mangled C++ name that looks like a game
    # symbol and is NOT on the list usually means a signature came out slightly different, which
    # is exactly the silent failure this tool exists to catch.
    suspicious = [s for s in (found - expected)
                  if s.startswith("?") and not s.startswith("??_") and "@@" in s
                  # Access_ helpers are generated by tools/genheaders.py so ported code can read a
                  # private static whose access is baked into its mangled name. They exist in no
                  # version of midtown2.exe, so they cannot mask an unported function.
                  # Only symbols the retail binary actually has can shadow original code. New
                  # names introduced by reimplementation - the whole agiGL* layer, and the
                  # generated Access_ helpers - exist in no version of the game.
                  and s in GAME_SYMBOLS]

    if suspicious:
        print()
        print("defined but not on the ported list - check for a signature mismatch:")
        for s in sorted(suspicious):
            print("  ?       %s" % s)

    print()
    if missing or suspicious:
        print("FAIL: %d missing, %d unexpected" % (len(missing), len(suspicious)))
        return 1

    print("all %d ported symbols present and correctly mangled" % len(matched))
    return 0


if __name__ == "__main__":
    sys.exit(main())
