# -*- coding: utf-8 -*-
"""Compile every generated header, so none of them can be wrong without anyone noticing.

WHY THIS EXISTS. tools/genheaders.py writes 534 headers. Only the ones some .cpp happens to
include are ever fed to a compiler, and the rest are checked by nothing at all - not their syntax,
not their check_size. Two separate bugs shipped that way in one afternoon:

  - array members were emitted as `gfxBitmap [10]* BitmapSpeeds;`, which is not C++. Three headers
    were invalid from the moment the kit layouts landed, and it surfaced only when porting
    mmLinearGauge finally caused one of them to be included.
  - a struct-typed member was sized at 4 bytes instead of 12, so `Vector3 Position` was followed by
    eight bytes of invented padding. aiRouteNode could not have satisfied its own check_size, and
    nothing said so, because nothing compiled it.

Both are exactly the class of error the rest of this build is built to make impossible, and both
got through for the same reason: a generated artefact that is never consumed is never verified.

WHAT IT DOES. Writes one translation unit that includes every header, and compiles it with the
same flags as the build. That catches a syntax error in any of them and every failing check_size
in one pass, in a few seconds - much faster than a header each, and self-containment falls out of
it: a header that needs another one included first fails here.

Run standalone, or as a build step:

    py tools/verify_headers.py
"""
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CODE = os.path.join(ROOT, "code", "midtown2")


def find(pattern, what):
    hits = sorted(glob.glob(pattern))
    if not hits:
        sys.exit("could not find %s (looked for %s)" % (what, pattern))
    return hits[-1]


def main():
    cl = find(r"C:\Program Files\Microsoft Visual Studio\*\*\VC\Tools\MSVC"
              r"\*\bin\Hostx64\x86\cl.exe", "cl.exe")
    msvc_inc = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.dirname(cl)))), "include")
    sdk_inc = find(r"C:\Program Files (x86)\Windows Kits\10\Include\*\ucrt",
                   "the Windows SDK headers")
    sdk_root = os.path.dirname(sdk_inc)

    headers = sorted(glob.glob(os.path.join(CODE, "**", "*.h"), recursive=True))
    if not headers:
        sys.exit("no generated headers under %s" % CODE)

    out = os.path.join(ROOT, "build")
    os.makedirs(out, exist_ok=True)
    tu = os.path.join(out, "allheaders.cpp")

    with open(tu, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/verify_headers.py. Every header, so that none of them can\n")
        f.write("// be invalid without a compiler saying so. Do not edit; do not commit.\n")
        for h in headers:
            rel = os.path.relpath(h, CODE).replace(os.sep, "/")
            f.write('#include "%s"\n' % rel)

    cmd = [cl, "-nologo", "-c", "-EHs-c-", "-O1", "-arch:IA32", "-W3", "-GS-", "-GR-", "-MT",
           "-Zc:sizedDealloc-", "-DARTS_AGIGL", "-DARTS_AGIGL_PHASE",
           "-I" + CODE, "-I" + msvc_inc, "-I" + sdk_inc,
           "-I" + os.path.join(sdk_root, "um"), "-I" + os.path.join(sdk_root, "shared"),
           "-Fo" + os.path.join(out, "allheaders.obj"), tu]

    res = subprocess.run(cmd, capture_output=True, text=True)
    text = (res.stdout or "") + (res.stderr or "")

    errors = [ln for ln in text.splitlines() if ": error " in ln]
    print("headers compiled : %d" % len(headers))

    if res.returncode == 0 and not errors:
        print("PASS: every generated header compiles, and every check_size holds")
        return 0

    # The FULL list goes to a file. Printing a capped list and counting the printed lines is how
    # "25 errors" got mistaken for the total through several rounds of fixing.
    log = os.path.join(out, "headers.log")
    with open(log, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    import collections
    by_header = collections.Counter()
    for ln in errors:
        head = ln.split("(")[0].strip()
        by_header[os.path.basename(head)] += 1

    print("\nFAIL: %d error(s) across %d header(s)" % (len(errors), len(by_header)))
    for name, n in by_header.most_common(20):
        print("  %-34s %d" % (name, n))
    if len(by_header) > 20:
        print("  ... and %d more headers" % (len(by_header) - 20))
    print("\nfull compiler output: %s" % log)
    print("\nA syntax error here is usually a bad member TYPE from data/layouts.json; a failing")
    print("check_size is usually a bad member WIDTH. See tools/kit_layouts.py.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
